version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs", "browser"]
  module_system = "es-modules"
  dialect = "typescript"
  skip_doc_coverage = ["class-expression", "method-definition"]
  cyclomatic_complexity_threshold = "high"
  style_guide = "airbnb"
